### ISSUE TITLE
Unable to build SWF file.

### ISSUE THREAD

**Issue by kosjak1** [dave-hansen/vpaidjs#4]
Hello! I've installed NodeJS(4.4.2)+grunt-cli(1.2.0)+grunt-air-sdk
When I try to "grunt build" I'm getting such output:

grunt build
Running "air_sdk:vpaidjs_swf" (air_sdk) task
/bin/sh: 1: -source-path: not found
/bin/sh: 1: -source-path: not found

Done, without errors.

After this, no swf file under dist directory.

**Comment by kosjak1** [comment]
Please close an issue, problem solved!

I've tried to install under root, so air_sdk was not installed.

Consider to run "**npm install --unsafe-perm**" if you're under root.

**Comment by dave-hansen** [comment]
Noted. I'll be sure to look into it. New release coming real soon.
